services:
  api_gateway:
    build: ./services/api_gateway
    container_name: omnishield_api_gateway
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - PHISHING_SERVICE_URL=http://phishing_service:8001
      - DEEPFAKE_SERVICE_URL=http://deepfake_service:8002
    depends_on:
      - phishing_service
      - deepfake_service
    env_file:
      - .env

  phishing_service:
    build: ./services/phishing_service
    container_name: omnishield_phishing_service
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env

  deepfake_service:
    build: ./services/deepfake_service
    container_name: omnishield_deepfake_service
    ports:
      - "8002:8002"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
